---
- name: Check that Service data directory at separated device
  include: check_data_drive.yml

- name: Add Service repository
  include: add_repository.yml

- name: Ensure of Service components are installed
  include: service_installed.yml

- name: Ensure of Service is enabled
  include: service_enabled.yml

- name: Placing of Service configuration
  include: service_configuration.yml

- name: Ensure of Service is Started
  include: service_started.yml
